controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


User_index:
    path: /api/users
    controller: App\Controller\UserController::index
    methods: GET

User_show:
    path: /api/users/{id}
    controller: App\Controller\UserController::show
    methods: GET

User_create:
    path: /api/users
    controller: App\Controller\UserController::create
    methods: POST

User_update:
    path: /api/users/{id}
    controller: App\Controller\UserController::update
    methods: PUT

User_delete:
    path: /api/users/{id}
    controller: App\Controller\UserController::delete
    methods: DELETE

Quiz_index:
    path: /api/quizzes
    controller: App\Controller\QuizController::index
    methods: GET

Quiz_show:
    path: /api/quizzes/{id}
    controller: App\Controller\QuizController::show
    methods: GET

Quiz_create:
    path: /api/quizzes
    controller: App\Controller\QuizController::create
    methods: POST

Quiz_update:
    path: /api/quizzes/{id}
    controller: App\Controller\QuizController::update
    methods: PUT

Quiz_delete:
    path: /api/quizzes/{id}
    controller: App\Controller\QuizController::delete
    methods: DELETE


Question_index:
    path: /api/questions
    controller: App\Controller\QuestionController::index
    methods: GET

Question_show:
    path: /api/questions/{id}
    controller: App\Controller\QuestionController::show
    methods: GET

Question_create:
    path: /api/questions
    controller: App\Controller\QuestionController::create
    methods: POST

Question_update:
    path: /api/questions/{id}
    controller: App\Controller\QuestionController::update
    methods: PUT

Question_delete:
    path: /api/questions/{id}
    controller: App\Controller\QuestionController::delete
    methods: DELETE


Answer_index:
    path: /api/answers
    controller: App\Controller\AnswerController::index
    methods: GET

Answer_show:
    path: /api/answers/{id}
    controller: App\Controller\AnswerController::show
    methods: GET

Answer_create:
    path: /api/answers
    controller: App\Controller\AnswerController::create
    methods: POST

Answer_update:
    path: /api/answers/{id}
    controller: App\Controller\AnswerController::update
    methods: PUT

Answer_delete:
    path: /api/answers/{id}
    controller: App\Controller\AnswerController::delete
    methods: DELETE


login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: POST

register:
    path: /register
    controller: App\Controller\RegisterController::register
    methods: POST