# config/services.yaml
parameters:
    photos_directory: '%kernel.project_dir%/public/img'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\UserProvider: ~

    # Define the circular reference handler
    serializer.circular_reference_handler:
        class: 'Closure'
        factory: ['Closure', 'fromCallable']
        arguments:
            - '@App\Service\CircularReferenceHandler'

    # To jest opcjonalne, jeśli chcesz zarejestrować tę klasę jako usługę
    App\Service\CircularReferenceHandler:
        arguments: []

# Framework serializer configuration
framework:
    serializer:
        enabled: true
        circular_reference_handler: 'serializer.circular_reference_handler'
